kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: go-web-app-ingress
  namespace: go-web-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: something.shubhamchugh.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-web-app-service
                port:
                  number: 8080