kind: Service
apiVersion: v1
metadata:
  name: go-web-app-service
  namespace: go-web-app
spec:
  selector:
    apps: go-web-app
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP